name: update visitors

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: fetch count & update readme
        run: |
          COUNT=$(curl -sS "https://api.counterapi.dev/v1/nekwasar/visitors/" | jq -r '.count // 0')

          sed -i "s/│ [0-9]\+ visitors/│ ${COUNT} visitors/" README.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            git add README.md
            git commit -m "bot: update visitor count (${COUNT})"
            git push
          fi
